"""Dream log: generate a summary of each dream session."""

import logging
import os
from datetime import datetime, timezone, timedelta

from config import DREAM_LOG_DIR

log = logging.getLogger("dreamer.log")

KST = timezone(timedelta(hours=9))


def write_dream_log(nrem_result: dict, rem_result: dict) -> str:
    """Write a dream log markdown file summarizing the session.

    Returns the path to the written log file.
    """
    os.makedirs(DREAM_LOG_DIR, exist_ok=True)

    now = datetime.now(KST)
    filename = now.strftime("%Y-%m-%d_%H%M") + ".md"
    filepath = os.path.join(DREAM_LOG_DIR, filename)

    lines = [
        f"# Dream Log -- {now.strftime('%Y-%m-%d %H:%M KST')}",
        "",
        "## NREM Phase (Episode -> Semantic)",
        "",
        f"- Episodes processed: {nrem_result.get('episodes', 0)}",
        f"- Chunks generated: {nrem_result.get('chunks', 0)}",
        f"- Clusters formed: {nrem_result.get('clusters', 0)}",
        f"- **New semantic memories: {nrem_result.get('created', 0)}**",
        f"- Duplicates skipped: {nrem_result.get('skipped_dup', 0)}",
        f"- Reference docs created: {nrem_result.get('docs_created', 0)}",
        "",
    ]

    dates = nrem_result.get("processed_dates", [])
    if dates:
        lines.append("### Processed Episode Dates")
        for d in dates:
            lines.append(f"- {d}")
        lines.append("")

    lines.extend([
        "## REM Phase (Integration + Pruning)",
        "",
        f"- Total semantic memories: {rem_result.get('total_memories', 0)}",
        f"- Conflicts found: {rem_result.get('conflicts_found', rem_result.get('contradictions', 0))}",
        f"- **Merged (state changes): {rem_result.get('merged', 0)}**",
        f"- **Consolidated (aspects): {rem_result.get('consolidated', 0)}**",
        f"- Deleted: {rem_result.get('deleted', rem_result.get('resolved', 0))}",
        f"- Split created: {rem_result.get('split_created', 0)}",
        f"- Importance decay applied: {rem_result.get('decayed', 0)}",
        f"- **Soft-deleted: {rem_result.get('soft_deleted', 0)}**",
        f"- Episodes archived: {rem_result.get('archived', 0)}",
        "",
    ])

    # Merge details
    merge_details = rem_result.get("merge_details", [])
    if merge_details:
        lines.extend(["### Merge Details (State Changes)", ""])
        for i, m in enumerate(merge_details, 1):
            lines.append(f"**{i}.** Before:")
            for before_text in m["before"]:
                lines.append(f"  - `{before_text[:100]}`")
            lines.append(f"  After: `{m['after'][:150]}`")
            lines.append("")

    # Consolidation details
    cons_details = rem_result.get("consolidation_details", [])
    if cons_details:
        lines.extend(["### Consolidation Details (Different Aspects)", ""])
        for i, c in enumerate(cons_details, 1):
            lines.append(f"**{i}.** Before:")
            for before_text in c["before"]:
                lines.append(f"  - `{before_text[:100]}`")
            lines.append("  After:")
            for after_text in c["after"]:
                lines.append(f"  - `{after_text[:150]}`")
            lines.append("")

    # Summary
    total_created = nrem_result.get("created", 0) + rem_result.get("split_created", 0)
    total_deleted = rem_result.get("deleted", rem_result.get("resolved", 0)) + rem_result.get("soft_deleted", 0)
    net = total_created - total_deleted

    lines.extend([
        "## Summary",
        "",
        f"- Net memory change: {'+' if net >= 0 else ''}{net}",
        f"  (created {total_created} - deleted {total_deleted})",
        "",
        "---",
        f"*Generated by Dreamer v0.2 at {now.isoformat()}*",
        "",
    ])

    content = "\n".join(lines)

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(content)

    log.info("Dream log written: %s", filepath)
    return filepath
